# For use in GitHub's Actions GUI
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
name: On-demand Packaging
on:
  workflow_dispatch:
    inputs:
      default_package_version:
        # TODO: see comment in ./package-pull-requests.yaml
        # It impacts whether this is a good string to show the user.
        description: 'Version string to use in any package format, if no more specific one is defined. Defaults to 0.0.0 to prototype.'
        default: '0.0.0'
        required: true
      git_ref:
        description: 'Git reference, like a branch name or commit hash'
        default: 'main'
        required: true
      deb_version:
        description: 'Version string to use for .deb packages. Defaults to default_package_version.'
        default: ${{ inputs.default_package_version }}
        required: false
      rpm_version:
        description: 'Version string to use for .rpm packages. Defaults to default_package_version.'
        default: ${{ inputs.default_package_version }}
        required: false
      pacman_version:
        description: 'Version string to use for pacman\'s .tar.gz format. Defaults to default_package_version.'
        default: ${{ inputs.default_package_version }}
        required: false
jobs:
  build-packages:
    uses: zyrolasting/pash/.github/workflows/packaging.yml@main
    with:
      default_package_version: ${{ inputs.default_package_version }}
      deb_version: ${{ inputs.deb_version }}
      rpm_version: ${{ inputs.rpm_version }}
      pacman_version: ${{ inputs.pacman_version }}
      git_ref: ${{ inputs.git_ref }}
    secrets: inherit
