# For use in GitHub's Actions GUI
# https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
name: On-demand Packaging
on:
  workflow_dispatch:
    inputs:
      fallback_version:
        # TODO: see comment in ./package-pull-requests.yaml
        # It impacts whether this is a good string to show the user.
        description: 'Fallback version string to use in any package format. Use 0.0.0 for throwaway prototypes. Compatibility not guarenteed for future formats.'
        default: '0.0.0'
        required: true
      git_ref:
        description: 'Git reference, like a branch name or commit hash'
        default: 'main'
        required: true
      deb_version:
        description: "Version string to use for pacman's .tar.gz format, if not the fallback."
        required: false
      rpm_version:
        description: 'Version string to use for .rpm packages, if not the fallback'
        required: false
      pacman_tgz_version:
        description: "Version string to use for pacman's .tar.gz format, if not the fallback."
        required: false
jobs:
  build-packages:
    uses: zyrolasting/pash/.github/workflows/package-build.yml@main
    with:
      fallback_version: ${{ inputs.fallback_version }}
      deb_version: ${{ inputs.deb_version }}
      rpm_version: ${{ inputs.rpm_version }}
      pacman_tgz_version: ${{ inputs.pacman_tgz_version }}
      git_ref: ${{ inputs.git_ref }}
    secrets: inherit
